### ISSUE TITLE
`compatto` throws a TypeError which says that the `dictionary` option is `undefined`

### ISSUE THREAD

**Issue by ghost** [macarie/compatto#6]
My first test is like:

var {compatto, DecompressError} = require('compatto')
var english = require("./node_modules/compatto/cjs/dictionary.cjs").dictionary
console.log(english.length) // outputs 254
console.log( Array.isArray(english)) //outputs true
const { compress, decompress } = compatto({ english })
const compressedString = compress("this is a string")
const decompressedString = decompress(compressedString)

console.log(decompressedString)

I am having

TypeError: The dictionaryoption must be an array with at most 254 elements. It isundefined.

thanks a lot !

**Comment by ghost** [comment]
My bad I should have put:

`compatto({ dictionary: english })`

All works fine ! 
thanks !

**Comment by macarie** [comment]
Yeah, the first argument is an object with `dictionary` as its (only) property.

Maybe I should've made it clearer in the docs.
